spring.application.name=legacy-shipping-service
server.port=8080
logging.pattern.console=%-5level [%X{traceId}] %logger{36} : %msg%n%ex{2}

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/shipping_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# External Carrier Endpoint (Mock)
external.carrier.url=http://localhost:8081/api/v1/rates/evaluate
